# Generated by Django 4.2.7 on 2023-12-07 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='Form',
        ),
    ]
